layout_spectrum: 0.9544688
typography_spectrum: 0.3165461
color:
  lightness: 0.05579843
  brandStrength: 1
  saturation: 0.09830949
  rhythmicContrast: 0.9988799
  brandColors:
    - '#FFFFFF'
    - '#3A5505'
    - '#687151'
    - '#A1AD88'
    - '#CED8B5'
name: GreenBean Coffee Imports
